# Site settings
title: uPi
name: KD # your name
email: xy@datamail.in # your email address
description: >
    Unified Program Interface. # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://upi.me" # the base hostname & protocol for your site
favicon: favicon.png
twitter_username: gpaidapps # your Twitter username
#github_username:  # your Github username
disqus_username: ooioo # your disqus username

#google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: pretty
markdown: kramdown
